delete from ledger_details;
delete from ledgers;
delete from tonkho;
delete from tonkho_tong;
delete from lichsuxnk;
delete from inv_report_detail;
delete from inv_report;
delete from mucgia;
delete from inventory;